language: c

os: linux
dist: trusty
# Use full depth for SonarCLoud
git:
  depth: false 

before_install:
  - wget -q -O - https://files.viva64.com/etc/pubkey.txt | sudo apt-key add -
  - sudo wget https://files.viva64.com/etc/viva64.list -O /etc/apt/sources.list.d/viva64.list

install:
  - sudo pip install gcovr
  - sudo apt-get update -qq && sudo apt-get install --assume-yes --quiet gcc-multilib && sudo apt-get install -qq
  - sudo apt-get install -qq pvs-studio 
  - sudo apt-get install -qq doxygen 
  - gem install ceedling
  - pvs-studio-analyzer credentials $PVS_USERNAME $PVS_KEY
  - |
    wget -q https://sourceforge.net/projects/astyle/files/astyle/astyle%203.1/astyle_3.1_linux.tar.gz/download -O astyle.tar.gz
    tar -xvf astyle.tar.gz
    cd astyle
    mkdir as-gcc-exe
    cd as-gcc-exe
    cmake  ../
    make
    sudo make install
    cd ../../

script:
  - |
    if [ ! -d "nRF5_SDK_15.3.0_59ac345/modules" ]; then
      wget -q https://developer.nordicsemi.com/nRF5_SDK/nRF5_SDK_v15.x.x/nRF5_SDK_15.3.0_59ac345.zip
      unzip -q nRF5_SDK_15.3.0_59ac345.zip
    fi
  - make astyle
  - git diff --exit-code --diff-filter=d --color
  - build-wrapper-linux-x86-64 --out-dir bw-output make all
  - ceedling test:all
  - ceedling gcov:all utils:gcov
  - gcov  -b -c build/gcov/out/*.gcno
  - sonar-scanner -Dsonar.projectVersion=$TRAVIS_TAG

cache:
  directories:
    - nRF5_SDK_15.3.0_59ac345
    - src/ruuvi.boards.c
    - src/ruuvi.drivers.c
    - src/ruuvi.endpoints.c
    - src/ruuvi.libraries.c

addons:
  sonarcloud:
    organization: "ruuvi" # the key of the org you chose at step #3
    projectKey: "ruuvi_ruuvi.firmware.c"

before_deploy:
  - sed -i '/doxygen/d' .gitignore
  
deploy:
  provider: pages
  cleanup: false
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  local_dir: doxygen/html
  edge: true
  on:
    branch: master