# This is a basic workflow to help you get started with Actions

name: GH-Pages-Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  doxygen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    # Install Doxygen
    - name: Install Doxygen
      run: sudo apt-get install -qq doxygen 

    # Generate doxygen
    - name: Generate docs
      run: doxygen

    - name: Install SSH Client ðŸ”‘
      uses: webfactory/ssh-agent@v0.5.2
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Deploy documents
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
          SSH: true
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: doxygen/html # The folder the action should deploy.
